// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  roomId: __t.string().name("room_id"),
  roundNumber: __t.u32().name("round_number"),
  hotseatPlayerId: __t.string().name("hotseat_player_id"),
  prompt: __t.string(),
  status: __t.string(),
  currentSubmissionId: __t.string().name("current_submission_id"),
  startedAtMs: __t.f64().name("started_at_ms"),
  endsAtMs: __t.f64().name("ends_at_ms"),
});
