// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  roomId: __t.string().name("room_id"),
  roundId: __t.string().name("round_id"),
  playerId: __t.string().name("player_id"),
  queueOrder: __t.u32().name("queue_order"),
  title: __t.string(),
  artist: __t.string(),
  album: __t.string(),
  albumCover: __t.string().name("album_cover"),
  releaseDate: __t.string().name("release_date"),
  durationMs: __t.u32().name("duration_ms"),
  spotifyUrl: __t.string().name("spotify_url"),
  previewUrl: __t.string().name("preview_url"),
  status: __t.string(),
  scoreTotal: __t.u32().name("score_total"),
  ratingCount: __t.u32().name("rating_count"),
  averageScore: __t.u32().name("average_score"),
});
