// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  playerId: __t.string(),
  roundId: __t.string(),
  submissionId: __t.string(),
  prompt: __t.string(),
  title: __t.string(),
  artist: __t.string(),
  album: __t.string(),
  albumCover: __t.string(),
  releaseDate: __t.string(),
  durationMs: __t.u32(),
  spotifyUrl: __t.string(),
  previewUrl: __t.string(),
  startedAtMs: __t.f64(),
  endsAtMs: __t.f64(),
};
