// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const GameRound = __t.object("GameRound", {
  id: __t.string(),
  roomId: __t.string(),
  roundNumber: __t.u32(),
  hotseatPlayerId: __t.string(),
  prompt: __t.string(),
  status: __t.string(),
  currentSubmissionId: __t.string(),
  startedAtMs: __t.f64(),
  endsAtMs: __t.f64(),
});
export type GameRound = __Infer<typeof GameRound>;

export const Person = __t.object("Person", {
  name: __t.string(),
});
export type Person = __Infer<typeof Person>;

export const Player = __t.object("Player", {
  id: __t.string(),
  roomId: __t.string(),
  name: __t.string(),
  identity: __t.identity(),
  isHost: __t.bool(),
  isReady: __t.bool(),
  isHotseat: __t.bool(),
  score: __t.u32(),
});
export type Player = __Infer<typeof Player>;

export const Rating = __t.object("Rating", {
  id: __t.string(),
  roomId: __t.string(),
  roundId: __t.string(),
  submissionId: __t.string(),
  playerId: __t.string(),
  score: __t.u32(),
});
export type Rating = __Infer<typeof Rating>;

export const Room = __t.object("Room", {
  id: __t.string(),
  joinCode: __t.string(),
  maxPlayers: __t.u32(),
  totalRounds: __t.u32(),
  status: __t.string(),
  hostIdentity: __t.identity(),
});
export type Room = __Infer<typeof Room>;

export const SongSubmission = __t.object("SongSubmission", {
  id: __t.string(),
  roomId: __t.string(),
  roundId: __t.string(),
  playerId: __t.string(),
  queueOrder: __t.u32(),
  title: __t.string(),
  artist: __t.string(),
  album: __t.string(),
  albumCover: __t.string(),
  releaseDate: __t.string(),
  durationMs: __t.u32(),
  spotifyUrl: __t.string(),
  previewUrl: __t.string(),
  status: __t.string(),
  scoreTotal: __t.u32(),
  ratingCount: __t.u32(),
  averageScore: __t.u32(),
});
export type SongSubmission = __Infer<typeof SongSubmission>;

