// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddReducer from "../add_reducer";
import AdvanceRoundReducer from "../advance_round_reducer";
import BeginRoundSetupReducer from "../begin_round_setup_reducer";
import CreateRoomReducer from "../create_room_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import SayHelloReducer from "../say_hello_reducer";
import SetReadyReducer from "../set_ready_reducer";
import StartRoundReducer from "../start_round_reducer";
import SubmitQueuedSongReducer from "../submit_queued_song_reducer";
import SubmitRatingReducer from "../submit_rating_reducer";

export type AddParams = __Infer<typeof AddReducer>;
export type AdvanceRoundParams = __Infer<typeof AdvanceRoundReducer>;
export type BeginRoundSetupParams = __Infer<typeof BeginRoundSetupReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type SayHelloParams = __Infer<typeof SayHelloReducer>;
export type SetReadyParams = __Infer<typeof SetReadyReducer>;
export type StartRoundParams = __Infer<typeof StartRoundReducer>;
export type SubmitQueuedSongParams = __Infer<typeof SubmitQueuedSongReducer>;
export type SubmitRatingParams = __Infer<typeof SubmitRatingReducer>;

