// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  roomId: __t.string().name("room_id"),
  name: __t.string(),
  identity: __t.identity(),
  isHost: __t.bool().name("is_host"),
  isReady: __t.bool().name("is_ready"),
  isHotseat: __t.bool().name("is_hotseat"),
  score: __t.u32(),
});
