// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  joinCode: __t.string().name("join_code"),
  maxPlayers: __t.u32().name("max_players"),
  totalRounds: __t.u32().name("total_rounds"),
  status: __t.string(),
  hostIdentity: __t.identity().name("host_identity"),
});
